# @name signUpAPI
POST http://localhost:4000/api/v1/auth/sign_up
Content-Type: application/json

{
    "email":"nihal+test2@cabbuddies.com",
    "password":"strong",
    "firstName":"Nihal",
    "lastName":"Konda"
}

###

@accessToken = {{signUpAPI.response.body.$.accessToken}}

###
# @name signInAPI

POST http://localhost:4000/api/v1/auth/sign_in
Content-Type: application/json

{
    "email":"nihal+test2@cabbuddies.com",
    "password":"strong"
}

###

@accessToken = {{signInAPI.response.body.$.accessToken}}


###
GET http://localhost:4000/api/v1/user
Content-Type: application/json

{
    "query":{
        "email": { "$regex": "1", "$options": "i" }
    }
}

###
GET http://localhost:4000/api/v1/user/me
Authorization: Basic {{accessToken}}

###
GET http://localhost:4000/api/v1/user/5f4c4eec9520541da7fdbe0a
Authorization: Basic {{accessToken}}
