POST https://cabbuddies-um.herokuapp.com/user/registration
Content-Type: application/json

{
    "email":"konda.nihal5@gmail.com",
    "password":"Mrox5497",
    "firstName":"Nihal",
    "lastName":"Konda",
    "phoneNumber":"9165139005"
}

###

POST https://cabbuddies-um.herokuapp.com/user/login
Content-Type: application/json

{
    "email":"konda.nihal5@gmail.com",
    "password":"Mrox5497"
}

###

GET https://cabbuddies-um.herokuapp.com/jwt/decode
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlODRmNGFlZTExYTY3MDAxNzVjMGUzOCIsImlhdCI6MTU4NTc3MjA4NCwiZXhwIjoxNTg1Nzc4MDg0fQ.3tes7BccxvFh00rZk0kjjf1-JWcWb3mQxeAj2oDiYro
