###
# @name signInAPI

POST http://localhost:4000/api/v1/auth/sign_in
Content-Type: application/json

{
    "email":"nihal+test1@cabbuddies.com",
    "password":"strong"
}

###

@accessToken = {{signInAPI.response.body.$.accessToken.value}}
@refreshToken = {{signInAPI.response.body.$.refreshToken.value}}

###

GET http://localhost:4000/api/v1/user/me
Authorization: Access {{accessToken}}

###

PUT http://localhost:4000/api/v1/user/
Authorization: Access {{accessToken}}
Content-Type: application/json

{
    "preferences": {
        "automaticFollow": true
    },
    "displayPicture": "randomer",
    "firstName": "Nihal",
    "lastName": "Konda"
}

###

GET http://localhost:4000/api/v1/user/5f59b8fc6368501be25f253e/relation
Authorization: Access {{accessToken}}

###

PUT http://localhost:4000/api/v1/user/5f59b8fc6368501be25f253e/relation/5fa468b14c3ff1791e9967bb
Authorization: Access {{accessToken}}
Content-Type: application/json

{
    "status":"rejected"
}